### ISSUE TITLE
Can this support panorama stereo?

### ISSUE THREAD

**Issue by dypromise** [huyaoyu/AirSim_SampleCubeClient#1]
Hi, seem to title, can this modification support output stereo 360?

**Comment by huyaoyu** [comment]
Hi, thank you for reaching out. 


The short answer is yes but might be slow. You can designate two cameras that at different locations and capture panorama images together. 

This whole project is one of our efforts to get panorama or omnidirectional images directly from AirSim. But the overall efficiency is not significantly better than taking 6 pinhole images and stitching them together. Besides, the current implementation will give you a rendered image that looks different than a pinhole image from AirSim. Especially you'll lose visual effects. 

So we stop doing this and use the 6-image way instead in our later development. Since we don't need real-time performance, it is good enough for us. Please visit tartanair.org for recent updates.
 https://tartanair.org/usage.html#customization

**Comment by dypromise** [comment]
> Hi, thank you for reaching out.
> 
> The short answer is yes but might be slow. You can designate two cameras that at different locations and capture panorama images together.
> 
> This whole project is one of our efforts to get panorama or omnidirectional images directly from AirSim. But the overall efficiency is not significantly better than taking 6 pinhole images and stitching them together. Besides, the current implementation will give you a rendered image that looks different than a pinhole image from AirSim. Especially you'll lose visual effects.
> 
> So we stop doing this and use the 6-image way instead in our later development. Since we don't need real-time performance, it is good enough for us. Please visit tartanair.org for recent updates. https://tartanair.org/usage.html#customization

Thank you so much for your guidance, I'll try tartanair-v2 API to generate ERP image first. It seems to re-project the raw data to the type I customized. 
And "So we stop doing this and use the 6-image way instead in our later development. Since we don't need real-time performance, it is good enough for us", the "later development" refers to tartanair-v2 dataset or new aimsim modification?
If I want to generate new data in my own sequence using airsim by myself( fisheye/ERP stereo too) instead of using tartanair-v2 dataset, the way  (1) use this repo? (2) use your new-developed 6 image stiching airsim repo? I will appreciate it if you give any guidance.

**Comment by huyaoyu** [comment]
Yes you are correct. The tartanair-v2 raw data is going to be in such a format that every camera is represented by 6-cameras covering all possible viewing angles. Then the customization API allows the user to reproject to any camera orientation with a bunch of camera models. You can also do the projection by yourself if you have a special camera model that is not already supported by our API.

Yeah, "later development" refers to tartanair-v2, which is at the end of development and we are drafting the paper now.

If you wan to collect new data, and you don't need it to be real-time, I suggest to use the new 6-image way. We are planning to release the entire data collection pipeline, if your schedule allows, you might want to consider to give it a try later.

**Comment by dypromise** [comment]
> Yes you are correct. The tartanair-v2 raw data is going to be in such a format that every camera is represented by 6-cameras covering all possible viewing angles. Then the customization API allows the user to reproject to any camera orientation with a bunch of camera models. You can also do the projection by yourself if you have a special camera model that is not already supported by our API.
> 
> Yeah, "later development" refers to tartanair-v2, which is at the end of development and we are drafting the paper now.
> 
> If you wan to collect new data, and you don't need it to be real-time, I suggest to use the new 6-image way. We are planning to release the entire data collection pipeline, if your schedule allows, you might want to consider to give it a try later.
Thanks. another question. On tartanair-v2's homepage, In the download example, I can only download ONE trajectory, could you tell me how to download the whole dataset? if it's not convenient now, could you send some indoor scene  trajectory to my email（nanhangdingyang@gmail.com）, I can't wait to try this data ：）
